### PR TITLE
Update for OSX build fix for GL header files.

### PR DESCRIPTION
**Pull request by ptulp**
Updates the GL header files needed for OSX build (See Issues)
Also updates the languages and data files available automatically.

### CODE REVIEW

**Comment by rgleason** [comment]
Thanks Peter. Sean will hopefully see this when he logs back in.

**Comment by lanceberc** [comment]
Thank you - I'd been deleting the missing polars manually. Did you create weather_routing_pi.pkgproj.in using the Packages app? Maybe renaming it afterwards?

**Comment by nohal** [comment]
The original version of the packaging project was created using Packages, then converted into a template which cmake fill.
Basically the template is exactly the same for any plugin, just differs in the filename.

**Comment by ptulp** [comment]
The latest pkgproj.in file used in this plugin and logbook and findit will take all the languages found in
build/Resources and all data files in directory data (if present) and place it in their respective directories
in the OpenCPN.app directory structure.

**Comment by rgleason** [comment]
Peter. I am trying to understand process. Is this for osx only? Thanks

**Comment by ptulp** [comment]
Yes, this file is only used to create a package for OSX.
The file is located in the buildosx/InstallOSX directory.

**Comment by seandepagnier** [comment]
Is anything in this pull request still needed for OSX?  If so, please resubmit without merge conflicts.  Closing for now.

**Pull request closed without merging**
