### PR TITLE
Fix crash on save polar

### PR DESCRIPTION
**Pull request by stelian42**

### CODE REVIEW

**Comment by stelian42** [comment]
Sean, please wait for Rick to confirm this fixes his problems on Windows too before merging.

**Comment by rgleason** [comment]
Yes, it is working!
Did several multiple adds to Rows and Cols. and did a routing.
screenshot 260
screenshot 262

jelly-beans

And more
jelly-bean-2

**Comment by stelian42** [comment]
Yum yum !

**Comment by rgleason** [comment]
Sean can you please merge?

**Pull request merged**
