### PR TITLE
MUI style icon, macOS installer

### PR DESCRIPTION
**Pull request by nohal**

### CODE REVIEW

**Comment by rgleason** [comment]
Pavel, I was just going to report that the MUI icon works, but I am still getting other icons dropping out.
The Icon still works you can click on it and the plugin starts. Then to recover the non mui icons I can hit the top of menu Bars and shrink and then click again and the icons rewrite and are no longer lost.

Now I see you have removed the Mui Icon, so I don't know what's going on or why..

**Comment by nohal** [comment]
Where do you see that, please?

**Comment by rgleason** [comment]
Sorry had to fetch the link.
https://travis-ci.org/rgleason/weather_routing_pi/builds/530934317?utm_source=github_status&utm_medium=notification

**Comment by nohal** [comment]
Where have I removed the MUI icon? I am not aware of doing anything like that.

**Comment by rgleason** [comment]
Well, there was a message that the PR I had made had had some more recent changes, and they are the ones I see here!

https://github.com/seandepagnier/weather_routing_pi/pull/244/commits/9be31fcc2691ec44827b45e5f9445bcdb4f51c88

So I guess I should make another pr to my repos?

**Comment by rgleason** [comment]
Sean can you merge this please?

**Comment by rgleason** [comment]
Thanks

**Pull request merged**
