### PR TITLE
Ability to stop computation of selected route

### PR DESCRIPTION
**Pull request by sebastien-rosset**
This is a partial enhancement for issue #172: When user clicks "Stop", it stops the computation of the selected routes, and does not reset the computation of other routes.

### CODE REVIEW

**Comment by rgleason** [comment]
@sebastien-rosset 
If my changes and PR from before have not been merged into Sean's then WR will have diverged and I will not be fixing this problem. Sorry.

**Comment by sebastien-rosset** [comment]
> If my changes and PR from before have not been merged into Sean's then WR will have diverged and I will not be fixing this problem. Sorry.

Can you elaborate? It looks like I missed something, but I'm not understanding. I'm new to OpenCPN contributions. Should have I raised the PR against your fork? I'm unclear which fork is actually used by the plugin manager.

**Comment by seandepagnier** [comment]
Rick,

I understand your frustration and you wont have to merge anything.    His changes are so far trivial anyway.

I thought I merged all your changes.   I do not see any PR from you.

**Comment by rgleason** [comment]
If Sean accepted all my PR's so that both reposirories were the same before your PR, then they will not diverge.

**Comment by rgleason** [comment]
At Sean, Good. I think we are probably ok then, as I likely made a PR back to your repository.

**Pull request merged**
