### PR TITLE
Boundaries

### PR DESCRIPTION
**Pull request by did-g**
Hi

Add land an boundary to reported errors, even if it's likely they'll always be reported if enable.

Add a small  offset to distance when testing for collision, help WR not getting stuck against a boundary

Try harder to properly end routing in the last step by:
- always  enabling 'optimize tacks' so it can reach end position even if upwind.
- it's not an error if there's land or boundaries on the tested heading but after destination, slow down WR a little.

WR still can't finish in at least 2 cases, one sending it in a wild goose chase  (if WR can't come close enough of destination).

I think fixing them need some kind of backtracking and variable time/degrees steps, also need for reliable coastal start.

Regards
Didier

### CODE REVIEW

**Comment by seandepagnier** [comment]
I don't like using a fixed distance of 0.05 in ll_gc_ll as it doesn't scale.   It may produce undesirable results in a different case.

What exactly is the problem with the current boundary detection?  What case does this solve?  I am trying to understand.

**Comment by did-g** [comment]
Hi

On Tue, Jan 30, 2018 at 5:02 AM, seandepagnier <notifications@github.com>
wrote:

> I don't like using a fixed distance of 0.05 in ll_gc_ll as it doesn't
> scale. It may produce undesirable results in a different case.
>
> What exactly is the problem with the current boundary detection? What case
> does this solve? I am trying to understand.
>
If an isochron ends right on a boundary line it often won't be able to move
on.

I don't think distance matter too much, what's need is some room for the
next propagation to go forward.

A contrive example with and without the heading (it's a different version
which try harder to move on collision by switching to smaller angular step
but it shouldn't matter you can get the same result by using a on degree
step):

**Comment by seandepagnier** [comment]
> If an isochron ends right on a boundary line it often won't be able to move
> on.
>

This is the idea, the boundary stops the propagation.

Maybe the boundary crossing logic is flawed somehow?

Allowing an extra 0.05 miles or any distance is cheating.
We aren't allowed in the boundary even by 1 meter.

> I don't think distance matter too much, what's need is some room for the
> next propagation to go forward.
>
> A contrive example with and without the heading (it's a different version
> which try harder to move on collision by switching to smaller angular step
> but it shouldn't matter you can get the same result by using a on degree
> step):

To navigate around those boundaries you need a much smaller time step,
or luck as the first picture shows.

**Comment by did-g** [comment]
Hi,

I'm not allowing an extra 0.05 miles, I'm removing  it or what I wrote is
not what I think and it's a bug.

**Comment by rgleason** [comment]
Did-g can you explain this statement a little further? I don't understand.
> Hi, I'm not allowing an extra 0.05 miles, I'm removing it or what I wrote is not what I think and it's a bug.

**Comment by did-g** [comment]
rgleason  

Currently a weather routing heading is invalid  if it's crossing a boundary edge, My goal with this patch is to stop if it's going to cross an edge in 0.05 nautical (I'm offsetting boundaries) but it's what I mean what the code actually do could differ if I wrote buggy code :)

Sean
Let this one off what about the others? If ok I will remove this from the PR.

Regards
Didier

**Comment by seandepagnier** [comment]
The other changes are ok

**Comment by did-g** [comment]
Ok,

I've rebased this PR without the head patch

Regards
Didier

**Pull request merged**
