### PR TITLE
Add wind barbs on the weather route

### PR DESCRIPTION
**Pull request by theeko74**
Add wind barbs along the route calculated by weather_routing.
The idea is to have a much better visualization of the wind direction and strength that we will get during the trip as grib visualizer only shows wind indication at a unique time point.

capture d ecran 2018-03-10 a 18 40 01

This option is selectable in Weather_Routing > View > Settings > Display Wind Barbs on Route.

capture d ecran 2018-03-10 a 18 38 49

### CODE REVIEW

**Comment by seandepagnier** [comment]
It appears to rebuild the line buffer every frame, rather than just if the routemap origin size changed.  Maybe not important for fast computers, but it would be nice to avoid.

You should call GetPlotData(false) rather than using the last_destination_plotdata variable.

Second, why are you Lock and Unlock?  This is not needed here.

Thanks for the contribution.

**Comment by rgleason** [comment]
You could also have the track change color based on boat speed, and also possibly have port and starboard represented by a second line in the proper color and along side of the route line on the appropriate side.

**Comment by seandepagnier** [comment]
Maybe these wind barbs should be a different color from the other wind barbs in case both settings are enabled?

I am wondering if it would be better to show wind arrows between the isochrons as well if they can fit?

What do you think?   It would require different code.  I will merge this for now.

**Comment by theeko74** [comment]
1/ I remove Lock/Unlock and use GetPlotData instead of last_destination_plotdata. Thanks for the tip.

2/ For cache implementation, I have an issue. When I use OpenGL to translate/rotate barbs following user screen, I get an unwanted translation of all barbs... See the pictures:

Without cache, barbs are correctly positioned:
capture d ecran 2018-03-11 a 03 53 50

With cache, barbs are translated to the right:
capture d ecran 2018-03-11 a 03 54 05

Any idea?

```
void RouteMapOverlay::RenderWindBarbsOnRoute(wrDC &dc, PlugIn_ViewPort &vp)
{
    /* Method to render wind barbs on the route that has been generated
     * by WeatherRouting plugin. The idead is to visualize the wind
     * direction and strenght at any step of the trip.
     *
     * Customization by: Sylvain Carlioz -- with Pavel Kalian's help ;-)
     * OpenCPN's licence
     * March, 2018
     */
    
    RouteMapConfiguration configuration = GetConfiguration();
    
    // if no route has been calculated by
    // WeatherRouting, then stops the method.
    // ([origin] is a list of all isochrons)
    if (origin.size() < 2)
        return;
    
    // if not, then check if wind barbs have been
    // already calculated and are stored in cache
    bool cache = origin.size() == wind_barb_route_cache_origin_size ||
                 vp.view_scale_ppm == wind_barb_route_cache_scale ||
                 vp.m_projection_type == wind_barb_route_cache_projection;
    
    // calculate wind barbs along the route by looping
    // over [last_destination_plotdata] which contains lat,
    // lon, wind info for each points.
    if (!cache)
    {
        wind_barb_route_cache_origin_size = origin.size();
        std::list<PlotData> plot = GetPlotData(false);
        std::list<PlotData>::iterator it;
        for (it = plot.begin(); it != plot.end(); it++)
        {
            wxPoint p;
            GetCanvasPixLL(&vp, &p, it->lat, it->lon);
            
            double VW = it->VW;
            double W = it->W;
            
            // Calculate the offset to put the head
            // of the arrow on the route (and not the
            // middle of the arrow) for readability.
            int xOffset, yOffset;
            xOffset = (int)(0.5 * 35 * sin(deg2rad(W)));
            yOffset = (int)(0.5 * 35 * cos(deg2rad(W)));
            
            // Draw barbs
            g_barbsOnRoute_LineBufferOverlay.pushWindArrowWithBarbs(
                wind_barb_route_cache, p.x + xOffset, p.y - yOffset, VW,
                deg2rad(W) + vp.rotation, it->lat < 0
            );
        }
        wind_barb_route_cache.Finalize();
    }
    
    // Draw the wind barbs, and use a cache
    // to avoid generating again the same wind barbs
    wxColour colour(180, 140, 14);
    wxPoint point;
    GetCanvasPixLL(&vp, &point, configuration.StartLat, configuration.StartLon);
    
    if(dc.GetDC())
    {
        dc.SetPen(wxPen(colour, 2));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
    }
    
#ifdef ocpnUSE_GL
    else
    {
        if(cache)
        {
            glPushMatrix();
            glTranslated(point.x, point.y, 0);
            glRotated(vp.rotation*180/M_PI, 0, 0, 1);
        }
        glColor3ub(colour.Red(), colour.Green(), colour.Blue());
        glEnable(GL_BLEND);
        glLineWidth(2);
        glEnableClientState(GL_VERTEX_ARRAY);
    }
#endif
    
    if(dc.GetDC())
    {
        if (cache)
        {
            LineBuffer tb;
            tb.pushTransformedBuffer(wind_barb_route_cache, point.x, point.y, vp.rotation);
            tb.Finalize();
            tb.draw(dc.GetDC());
        }
        else
        {
            wind_barb_route_cache.draw(dc.GetDC());
        }
    } else
        wind_barb_route_cache.draw(NULL);

#ifdef ocpnUSE_GL
    if(!dc.GetDC())
    {
        glDisableClientState(GL_VERTEX_ARRAY);
        if(cache)
            glPopMatrix();
    }
#endif
    
}
```

**Comment by theeko74** [comment]
@seandepagnier :
- To change the wind barbs color is a good idea. Not difficult to implement ;-)
- Why showing wind barbs between the isochrons? For a better visualization?
Thanks for merging.

**Pull request merged**
