### PR TITLE
Use OpenCPN Waypoint in WR.

### PR DESCRIPTION
**Pull request by did-g**
Hi,
Use new O menu cability for using standard way point in WR.
When WR is open a new entry is added to Waypoint menu 'Weather route position' and a waypoint can be used as a WR position.
It's a reference not a copy, moving the WP or renaming it update WR position. 

It needs more work because It's a bit confusing, there's now two kinds of position in WR.
missing is way for hiding WP  when WR route is not selected, ie like with 'classic' WR position.
 
Regards
Didier

### CODE REVIEW

**Comment by rgleason** [comment]
Did-g this works! 
1. Create a WP and Name it.
2. Start WR and Grib and Climatology
3. Right click the waypoiint and Pick Weather_Routing Position

It works!
screenshot 83

**Comment by rgleason** [comment]
Didier,  I forgot to say that there is a little problem with the selected way point appearing in weather_routing after you select it. 
I have to close down Opencpn and reopen it then open Weather_routing and the waypoint makes it into the WRouting list of waypoints.

See added not above.

**Comment by did-g** [comment]
I'm not sure it's this PR, there's something fishy going on with WR dialog:
- you have to use a right click for selecting a row in position list.
- sometime it seems WR dialog grab the pointer and you can't move waypoint
and so one.

**Comment by rgleason** [comment]
Didier,
Is what you are thinking shown above in the waypoint properties?
Where it says "Main Menu" which you right click?
Perhaps it is another location where it is like that???
-------------
The real problem I have with this is you have to shutdown WR and Opencpn and reopen before you see the added Waypoint.
------------

**Comment by did-g** [comment]
Two think are briken with config dialog box:
- since android modif, only a right click can select a position
- on window, left clicks on the canavas are sometime delayed until config dialog is closed

**Pull request merged**
