### PR TITLE
Various

### PR DESCRIPTION
**Pull request by nohal**
- Translations
- Packaging
- CI integration (Untested)

- Please tag a release when ready

### CODE REVIEW

**Comment by stelian42** [comment]
Pavel,

Is there a reason why you did change -O2 into -O0 in the "Packaging" commit ?

**Comment by nohal** [comment]
Don't remember, we should probably try to put -O2 back.

**Comment by stelian42** [comment]
Ok, done in #183

**Comment by rgleason** [comment]
I'll wait until to compile until it is merged. (Appveyor failed due to binaries not downloading from Sourceforge).

**Pull request merged**
