### PR TITLE
ADD comfort status in the WeatherRouting panel and ReportDialog

### PR DESCRIPTION
**Pull request by theeko74**
I propose to add the sailing comfort indication in the WeatherRouting table and in the Report.
This allows to:
* Display directly in the table what will be the worst sailing comfort conditions found on the way.
capture d ecran 2018-06-11 a 13 07 04

* Display in the ReportDialog the most comfortable route and date to start
capture d ecran 2018-06-11 a 13 12 20

### CODE REVIEW

**Comment by seandepagnier** [comment]
Is "Best Sailing Comfort" the best of the worst?  This is confusing.  Can we improve?   What about "Least Uncomfortable route"?    What about listing all the dates that sailing comfort is good?

**Comment by theeko74** [comment]
Hi Sean,

My idea was:
* We want to sail with the best sailing comfort which means: wind not so strong (<27knts), route not so upwind, waves not so big (<5m)
* We want to start as soon as possible

So, report shows the best comfort level (between good, bumpy, difficult) and the soonest date to leave.

For example:
* If all routes are evaluated as difficult on June 1, 2, 3, report will say:

> Best Sailing Comfort: difficult on June 1

* If there are 3 routes, 1 difficult on June 1, 1 good on June 2, 1 good June 3, report will say:

> Best Sailing Comfort: good on June2

I think "Least Uncomfortable route" is more confusing than "Best sailing comfort"..
Maybe we can use:
1) Best Time with best sailing comfort?
2) Best Time (most comfortable) ?
3) Best comfortable route?

What do you think?

**Comment by rgleason** [comment]
This may be a different issue, but I have several friends that request Racing routings, which do not involve comfort so much (although that is also  of interest). I haven't thought about this enough, but  is there a way to control the routings for greater comfort or greater speed?  I imagine this would be done through adjusting the polar file.

**Comment by theeko74** [comment]
Hi Rick,

The idea is to do exactly the opposite ;-) Most of people don't race... They want to use it to optimize their trip, find the best weather window to get good sailing conditions (10-20knots of wind, no wave, preferably donwind, etc.). 

If you want to optimize your route to get better sailing comfort, you can use the option "Max True Wind" and "Max Apparent Wind" to reduce it to the maximum acceptable by the crew.
For example, you can compute:
* Route #1: unlimited max apparent wind to see the fastest route
* Route #2: max apparent wind = 20knots 
And of course you can easily check the difference of time and sailing comfort.
Most of the time you will see the most comfortable route is a bit longer but I guess some people don't care to loose few hours on a sailing trip...
So, what do you think?

**Comment by rgleason** [comment]
Theeko,  First I really like all that you have done. It has improved our understanding of a given routing tremendously.

I agree that most people don't race and want to find the best weather window and routing with better comfort, when I cruise this is what I generally want. 

When I race, I want to be able to use this plugin for that too, and I would like to to remain a multi-blade  blade tool, and a generalized solution for different types of uses. 

Sean has provided that we are able to set constraints, and I have not used that extensively and should start doing so.

However this leads to how to have easily changed options for route optimization display of various values for different purposes or better understanding. Perhaps having the ability to show any of these values along the route  comfort level, boat speed, wind speed, wave period, wave height with  with changing colors?

**Comment by theeko74** [comment]
If you don't want to see the comfort in dialog configuration you can deselect in settings.
I agree we should keep in mind both functions race and cruising.
But I think one way to differentiate from other routing software is for the cruising application with less software doing that...

**Comment by rgleason** [comment]
Yes, I agree that having good cruising tools is a good strategy, however skilled cruisers will want to quickly change or view the optimized route for various conditions [comfort level, boat speed, wind speed, wave period, wave height, etc] with with changing colors or some other tabular format.

I just did a routing Newport to Horta changing the constraints and it did change the comfort levels and route quite nicely.

I would only uncheck "Comfort Level" if there were other conditions that could be shown easily.

max-true-22-max-app-28
max-true-100-max-app-100

**Comment by did-g** [comment]
Hi
It seems to me what you want is more knobs in batch generator dialog.

**Comment by rgleason** [comment]
Would that require re-running Compute?  
Right now  am thinking of a Button or shortcut key to scroll through a series of weather variables, such that the selected variable shows color coded on the optimized route. It would be nice if the weather variable was identified somehow.

**Comment by seandepagnier** [comment]
At some point we are probably going to want to define a polar to specify comfort levels since they vary depending on the boat.  Will merge for now, and I agree that it is nice to produce reports useful for cruising rather than racing.   Eventually, settings for the report generator for cruising or racing, or even more options.

It also might be worth considering that if conditions are "difficult" for just a few hours vs "moderate" for days, this may be prefered, you can simply heave-to during that period, but this is not covered in weather routing constraints yet.

It is already possible to define different boats, some that heave-to in difficult conditions, so at some point there becomes an overlap in functionallity, but how to make it easy to use I am not sure.

**Comment by rgleason** [comment]
"already possible to define different boats, some that heave-to in difficult conditions,"
By putting a very small  (0 .1) value  in higher TWS ?

**Pull request merged**
