### PR TITLE
Add sailing comfort indicator on weather route

### PR DESCRIPTION
**Pull request by theeko74**
Display sailing comfort level directly on the weather route. The idea is to visualize directly what sailing conditions will be met during the trip:
* Green = Light conditions, relax and enjoy
* Orange = Can be tough, stay focus
* Red = Strong conditions, heavy sailors, be prepared !

capture d ecran 2018-03-14 a 12 36 25

This is an option (non activated by default):

capture d ecran 2018-03-14 a 12 36 11

### CODE REVIEW

**Comment by theeko74** [comment]
@did-g 
I cannot open `WeatherRouting.fbp` with wxFormBuilder.
I got the following error:
capture d ecran 2018-03-14 a 12 42 37
Any idea why?

**Comment by nohal** [comment]
Too old a version. You need the very latest wxFB code, with https://github.com/wxFormBuilder/wxFormBuilder/pull/351 included.
On macOS I strongly suggest to build against wx3.1.1 as it solves a whole lot of other problems...

**Comment by theeko74** [comment]
Improve quality of the circle which represents the boat.

Before:
capture d ecran 2018-03-14 a 14 28 09

After:
capture d ecran 2018-03-14 a 14 32 31

**Comment by theeko74** [comment]
thanks @nohal it works now

**Pull request merged**
