### PR TITLE
Refactor the Weather routing window to use a wxCollapsiblePane

### PR DESCRIPTION
**Pull request by nohal**
Allows one-click collapsing/expanding the main weather routing window.
screen shot 2018-02-18 at 20 40 26
screen shot 2018-02-18 at 20 40 17

Of course works best on platforms with detached menu bar (macOS, default Ubuntu etc.), on Windows and similar we could consider, optionally, hiding the menu in collapsed mode to let the user prevent stuff like this:
virtualbox_windows 10_18_02_2018_21_16_44

### CODE REVIEW

**Comment by seandepagnier** [comment]
It sure seems to take a lot of window space up when it's unrolled.

How to more strategically place the ^  button?

**Comment by nohal** [comment]
We can't. Without completely reimplementing wxCollapsiblePane, which I would avoid.

**Comment by seandepagnier** [comment]
Can we just use a normal toggle button?   Maybe it can be in the lower
right after the progress bar?

If nothing else, it should be an optional feature.   It wastes a lot
of space of the dialog.

**Comment by nohal** [comment]
For a normal user, this feature generates a lot of space on screen as you can see from the discussion on CF, but as you wish, do not merge like this and I will eventually have a look if it is reasonably simple to make it optional...
Not using standard controls and moving it to lower right corner or some other illogical place would of course "save space", but is an ergonomic disaster IMO, not just extra work.

**Comment by nohal** [comment]
Updated the PR to make it optional, set `DisableColPane` to `1` in `[PlugIns/WeatherRouting]` to disable the collapsible pane and use the old behaviour where the full window must be shown.

**Pull request merged**
