### PR TITLE
ADD apparent wind for WindBarbsOnRoute

### PR DESCRIPTION
**Pull request by theeko74**
Change from true wind direction and speed to apparent wind direction
and speed as it is the conditions that we have on the boat...
For example, it helps to see if we can do upwind or not.

### CODE REVIEW

**Comment by rgleason** [comment]
Sounds reasonable to me. Does it conflict with anything else in the plugin?
The grib files show True wind.  The boat feathers at optimal route would now show Apparent?

**Comment by theeko74** [comment]
This will not impact any thing in the plugin as it is only related to WindBarbOnRoute option.

**Comment by rgleason** [comment]
I hope Sean will merge. Thank you. I'll add a note in manual when he does so.

**Comment by seandepagnier** [comment]
It is supposed to show true wind, not apparent wind.

**Comment by theeko74** [comment]
You're right @seandepagnier can you tell me if this is fix now and showing apparent wind (and not true wind)? Thanks

**Comment by seandepagnier** [comment]
I don't have a problem to make this a display option, but by default, wind barbs rendered on the chart are understood to mean true wind, not apparent wind.

**Comment by theeko74** [comment]
OK, this is now an option + WindBarbsOnRoute have a blue color to distinguish from default true wind.
What do you think?

**Comment by theeko74** [comment]
By the way @seandepagnier I am sorry but the other PR #226 includes the old version of apparent windBarbsOnRoute... If you merge this PR this should solve it.

**Pull request merged**
