### PR TITLE
Grib backport

### PR DESCRIPTION
**Pull request by did-g**
Hi,

- backport unrelated stuff from grib plugin record so grib and weather_routing source code don't diverge to much.
- use new grib class format once, or if, integrated in opencpn.
- use smart pointers and a weakly referenced grib record table for sharing grib record between configurations, if it's committed, it needs some cleanup, this commit trying to change as little as possible code.

I'm hijacking plugin API version for testing grib record format change...

For testing on linux adding plugins as subtree is the easiest.  My default branch https://github.com/did-g/OpenCPN.git have a bunch of subtree plugins , may have too much unrelated WIP changes though.

Regards
Didier

### CODE REVIEW

**Comment by rgleason** [comment]
Did-g, can I make a pr and merge, and it will work?  It sounds like Sean needs to do some additional programming, and we will need a new api115.  No problem there, but doesn't OpenCPN Alpha needs to have it too?

**Comment by did-g** [comment]
Hi,
API version 115 is already in Dave's master branch but you need both ocpn and weather routing PR pull/merge .

Unless you are trying to compute route with big grib or very small time steps (ie many interpolated records) this PR have no visible change. 

I wouldn't spend time on it.

Regards
Didier

**Comment by rgleason** [comment]
Thanks, I am using th Alpha version now, so I guess I'll merge it next time, or when Sean does.

**Comment by seandepagnier** [comment]
Are there any measured performance improvements from shared pointers here?

Is this safe to merge... will it be compatible with older grib plugins, or do we need to check the grib plugin version?

**Comment by did-g** [comment]
Hi,
There's a small speed improvement but the main advantage is that on a 32 bits system for big gribs without sharing records weather_routing reach 4 GB limit a lot earlier. 
By using less memory there's another improvement even on 64 bits system:
Currently opencpn purges its charts cache if the whole process memory is closed to a 1 GB limit.
Even without very big grib or a lot of computed routes it can really slowdown opencpn to a point where restarting opencpn is the only option left.

This version isn't  compatible with 4.8.0 there's no need for testing because API version 115 is not release yet and this version will fail to load on 4.8.0 or older.

If you want to release a new weather_routing version for released O version don't merge this PR.

**Comment by seandepagnier** [comment]
You must be using full world gribs or very high resolution?   What is
your source of gribs?


Maybe the plugin could request subsets of grib files to reduce the
memory load as well?

I _may_ release a new version soon, so I will hang onto this PR for nwo.

**Comment by did-g** [comment]
My grib source? The best, me :)

I'm using Meteo France for hourly wind 0.01° and IFREMER for 15 mn current 0.0023° .
for example:
http://195.154.231.142/IFREMER/MANW250.grb
it's a 60MB for a 4x2 degrees 15 hours...

I'm having fun trying to find if it's worth it.

**Comment by seandepagnier** [comment]
There was no release, so I am ready to merge this, if you can resolve the conflicts.

**Comment by did-g** [comment]
Hi,
This PR is not compatible with current OpenCPN record format.

I'm pushing a second change with only gribrecord modifications since previous copy and paste gribrecord code in weather routing, if you commit this PR I will update this one (still trying to find a way to stay compatible with current OpenCPN).

Regards
Didier

**Comment by seandepagnier** [comment]
I will merge if you can resolve conflicts.

**Comment by seandepagnier** [comment]
ok. waiting until opencpn (in git master) is ready.

**Comment by rgleason** [comment]
What was this PR #132 Grib Backport Grib record changes from Opencpn for?
https://github.com/seandepagnier/weather_routing_pi/commit/078c4d1814dc904eac2865136772a95bb1fd768e

**Comment by did-g** [comment]
Weather routing  is using some files from Opencpn main source code, by
copying them.

In 4.8.2 theses files have been slightly modified without breaking
compatibility with older versions.
#132 copy back them in weather routing.
It's not a mandatory change but by keeping both versions as close as
possible it'd make life easier down the line; both for understanding code
and in the case some incompatible changes have to be made.

**Comment by rgleason** [comment]
On Feb 8 Sean merged #133 Error in Boundary which keeps compatibility with 4.8.2 and earlier.

On  Dec 30,2017 Did-g wrote:
 ```
This version isn't compatible with 4.8.0 there's no need for testing because API version 115 is not release yet and this version will fail to load on 4.8.0 or older.
If you want to release a new weather_routing version for released O version don't merge this PR.
```
So I believe that  Grib Backport #111 this should not be merged until we move on to wxWidgets 3.1.1 and working at the head on API 16 and v4.99.

**Comment by seandepagnier** [comment]
Is this ready to merge or should we wait for O5 release?

**Comment by did-g** [comment]
Hi,
It's missing O5 Appveyor dependencies but otherwise yes it's ready to merge.

**Comment by did-g** [comment]
Hi,
Should have right dependencies for Windows and OSX CI build.

**Pull request merged**
