### PR TITLE
Made updates to be able to build and run on OSX. 

### PR DESCRIPTION
**Pull request by ptulp**
Updated BoatPlan.cpp as OSX doesn’t like only message i.s.o. message.empty().
Updated WeatherRouting.cpp as OSX does not work with a Timer start of 0 microseconds so I changed that to 1 micro.

### CODE REVIEW

**Comment by nohal** [comment]
Peter...
There is a little problem - The OS X package does not contain the needed data files. It means editing that awful proect file - I will have a look at it when I have time, but if you are faster, better ;)

**Comment by seandepagnier** [comment]
Maybe you could split the project file into one which is identical for all plugins, and a second which specifies specific files and is somehow included?

**Comment by nohal** [comment]
Yes, that's the plan, I just didn't have time to do it yet - the project file contains XML serialized objects, so it definitely is possible, but not totally straightforward. A few nested templates will do.

**Comment by ptulp** [comment]
Until Pavel comes up with a perfect version, I created a crude update to put the files in the package.

**Comment by ptulp** [comment]
Found out that to include the data files you only need to update the pkgproj.in file.
No updates needed in the Plugin*.cmake files.

**Comment by seandepagnier** [comment]
It would sure be nice if you could autogenerate the pkgproj.in file so that
it doesn't have to be manually edited.  This should be possible using cmake
variables.

**Pull request merged**
