### PR TITLE
Change comfort model and scoring for comfort on route option

### PR DESCRIPTION
**Pull request by theeko74**
First implementation of the comfort scoring for comfort on route option was wrong as in some cases with low wind course 30° form wind, we reach comfort zone red...

So I made some changes in the scoring system. Of course, this is very empirical (how to do otherwise?), and based on my proper sailing experience but changes include:
* Course over wind score is changed to a normal distribution center on 30°, as maximum incomfort is felt when sailing on the wind (30-40°);
* Wind and waves scores are changed to an exponential function (see curves bellow).

capture d ecran 2018-03-15 a 17 42 52

I am an amateur sailor. The "comfort" is probably different for professionals or "sailors around the world". I made several tests and it looks OK for me.

What do you think?

### CODE REVIEW

**Comment by seandepagnier** [comment]
Because this change is purely visual and optional, I don't mind.  Change as you see fit.

**Comment by theeko74** [comment]
You're right it is visual but it could be used in a wrong way like "Okay, everything is green, I can go" and does not look carefully the weather. So I tried to make something not too optimistic. Thanks for merging.

**Comment by rgleason** [comment]
Has anyone noticed slow/reluctant  panning, zooming and grab & drag?
I have with the most recent change. Don't know if it is something else about my computer, but it happens when using WxRte_pi with rendered route optimizations showing with optimal route feathers on and the most recent comfort indicator.  I should try it with these off too.

**Comment by rgleason** [comment]
I'd like to advise that the pan/zoom/move problem must have been due to computer low memory.

Also there never has been a Tooltip, yellow information popup along the route. Skipperearly, want to enter this into Tracker? Besides est time/date there would be some other useful info to add.

**Pull request merged**
